// stdafx.h


#include <algorithm>
#include <cassert>
#include <cctype>
#include <climits>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <functional>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <typeinfo>
#include <vector>

#include <base_screen.h>
#include <base_struct.h>
#include <base_units.h>
#include <bitmaps.h>
#include <common.h>
#include <confirm.h>
#include <eda_base_frame.h>
#include <eda_draw_frame.h>
#include <gal/color4d.h>
#include <gal/definitions.h>
#include <gal/gal_display_options.h>
#include <gal/stroke_font.h>
#include <kicad_string.h>
#include <pgm_base.h>

#include <wx/artprov.h>
#include <wx/bitmap.h>
#include <wx/button.h>
#include <wx/colour.h>
#include <wx/dialog.h>
#include <wx/filename.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/grid.h>
#include <wx/html/htmlwin.h>
#include <wx/log.h>
#include <wx/panel.h>
#include <wx/textctrl.h>
#include <wx/tokenzr.h>