// stdafx.h

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <deque>
#include <functional>
#include <iostream>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <regex>
#include <set>
#include <sstream>
#include <string>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <boost/ptr_container/ptr_map.hpp>
#include <boost/ptr_container/ptr_set.hpp>
#include <boost/ptr_container/ptr_vector.hpp>
#include <boost/range/adaptor/map.hpp>

#include <board_connected_item.h>
#include <class_board.h>
#include <class_board_item.h>
#include <class_dimension.h>
#include <class_drawsegment.h>
#include <class_edge_mod.h>
#include <class_marker_pcb.h>
#include <class_module.h>
#include <class_pad.h>
#include <class_pcb_target.h>
#include <class_pcb_text.h>
#include <class_text_mod.h>
#include <class_track.h>
#include <class_zone.h>
#include <collectors.h>
#include <layer_widget.h>
#include <netinfo.h>
#include <netlist_reader.h>
#include <pcb_edit_frame.h>
#include <specctra_import_export/specctra.h>
#include <tools/drc.h>
#include <tools/pcb_actions.h>
#include <tools/selection_tool.h>

#include <wx/artprov.h>
#include <wx/string.h>
#include <wx/arrstr.h>
#include <wx/button.h>
#include <wx/bitmap.h>
#include <wx/checkbox.h>
#include <wx/choice.h>
#include <wx/colour.h>
#include <wx/config.h>
#include <wx/dialog.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/grid.h>
#include <wx/image.h>
#include <wx/intl.h>
#include <wx/icon.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/radiobox.h>
#include <wx/radiobut.h>
#include <wx/regex.h>
#include <wx/string.h>
#include <wx/settings.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/statline.h>
#include <wx/textctrl.h>
#include <wx/valnum.h>
#include <wx/valtext.h>
#include <wx/xml/xml.h>
#include <wx/xrc/xmlres.h>