// stdafx.h

#pragma once

#include <algorithm>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <unordered_set>
#include <vector>

#include <class_libentry.h>
#include <class_library.h>
#include <lib_arc.h>
#include <lib_bezier.h>
#include <lib_circle.h>
#include <lib_edit_frame.h>
#include <lib_manager.h>
#include <lib_pin.h>
#include <lib_polyline.h>
#include <lib_rectangle.h>
#include <lib_text.h>
#include <netlist_object.h>
#include <sch_bus_entry.h>
#include <sch_component.h>
#include <sch_component.h>
#include <sch_edit_frame.h>
#include <sch_junction.h>
#include <sch_line.h>
#include <sch_no_connect.h>
#include <sch_sheet.h>
#include <sch_sheet_path.h>
#include <sch_base_frame.h>
#include <sch_bitmap.h>
#include <sch_bus_entry.h>
#include <sch_draw_panel.h>
#include <sch_field.h>
#include <sch_item.h>
#include <sch_marker.h>
#include <sch_painter.h>
#include <sch_reference_list.h>
#include <sch_text.h>
#include <sch_view.h>

#include <boost/ptr_container/ptr_map.hpp>
#include <boost/ptr_container/ptr_set.hpp>
#include <boost/ptr_container/ptr_vector.hpp>
#include <boost/range/adaptor/map.hpp>

#include <wx/artprov.h>
#include <wx/string.h>
#include <wx/arrstr.h>
#include <wx/button.h>
#include <wx/bitmap.h>
#include <wx/checkbox.h>
#include <wx/choice.h>
#include <wx/colour.h>
#include <wx/config.h>
#include <wx/dialog.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/grid.h>
#include <wx/image.h>
#include <wx/intl.h>
#include <wx/icon.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/radiobox.h>
#include <wx/radiobut.h>
#include <wx/regex.h>
#include <wx/string.h>
#include <wx/settings.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/statline.h>
#include <wx/textctrl.h>
#include <wx/valnum.h>
#include <wx/valtext.h>